config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments, only: [:create, :destroy]
  end

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@article = Article.find(params[:article_id])
  	if @article.comments.create(comment_params)
  	  redirect_to article_path(@article.id)
    else
      render 'articles/show'
    end
  end
=begin
  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy
  	redirect_to article_path(params[:article_id])
  end
=end
  private

    def comment_params
      params[:comment].permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title, size: 25 %>
  </div>
  <div>
    <%= f.label :content %><br>
    <%= f.text_area :content, cols: 50, rows: 7 %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>記事編集</h1>

<%= render 'form' %>

<br>

<%= link_to '記事を見る', @article %> |
<%= link_to '戻る', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<div id="index-title">
  <h2>記事一覧</h2>
  <i class="fa fa-pencil-square-o"></i>
  <%= link_to '新規記事作成', new_article_path %>
</div>

<ul id="index-ul">
  <% @articles.each do |article| %>
    <li id="index-li">
      <%= link_to article.title, article %><br>
      <span class="created-time">
        <%= article.created_at %>
      </span>
    </li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h2 id="new-title">新規記事作成</h2>

<%= render 'form' %>

<br>

<%= link_to '戻る', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p id="show-title">
  <%= @article.title %><br>
</p>

<p id="show-content">
  <%= @article.content %>
</p>

<p class="created-time">
  <%= @article.created_at %>
</p>

<p id="show-write-comment">コメントを書く</p>
<%= form_for [@article, @article.comments.build] do |f| %>
<%= f.text_area :body, cols: 35, rows: 5 %><br>
<%= f.submit "投稿", id: "show-submit" %>
<% end %>

<p id="show-comment-index">コメント一覧</p>
<ul>
  <% @article.comments.each do |comment| %>
    <li>
      <%= comment.body %>

      <% if false %>
	  <%= link_to '[Delete]', article_comment_path(comment.article_id, comment.id), method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>

    </li>
  <% end %>
</ul>

<div class="links">
<%= link_to 'Home', articles_path %> |
<%= link_to '編集', edit_article_path(@article) %> |
<%= link_to '削除', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header">
    <h1>はじめてのブログ</h1>
  </div>

  <div class="container">
	<%= yield %>
  </div>
</body>
</html>